package report

import (
	"encoding/json"
	"encoding/xml"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/Shadow-Security-official/Shadow-Armor/internal/model"
	"github.com/Shadow-Security-official/Shadow-Armor/internal/score"
)

// Formats accepted by -o / --format.
var Formats = []string{"text", "json", "html", "sarif", "junit", "markdown"}

// JSON writes the full Shadow-Armor report.
func JSON(w io.Writer, r *model.Report) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(r)
}

// Markdown writes a summary suited to pull requests, tickets and chat.
func Markdown(w io.Writer, r *model.Report) error {
	s := r.Summary
	scoreTxt := "n/a"
	if s.Score != nil {
		scoreTxt = fmt.Sprintf("%.1f", *s.Score)
	}
	fmt.Fprintf(w, "## Shadow-Armor: grade **%s** (score %s/100)\n\n", s.Grade, scoreTxt)
	fmt.Fprintf(w, "`%s` · %s %s · %s %s (%s) · level %d · %s · %d controls\n\n",
		r.Target.URI, r.Target.Platform.Name, r.Target.Platform.Release, r.Engine.Name, r.Engine.Version, r.Engine.Mode,
		r.Selection.Level, stdName(r, s.Lens), r.Selection.Count)
	for _, c := range s.Caps {
		fmt.Fprintf(w, "> Capped at **%s**: %s (%s)\n", c.Grade, c.Reason, idList(c.IDs, 6))
	}
	if len(s.Caps) > 0 {
		fmt.Fprintln(w)
	}
	c := s.Counts
	fmt.Fprintf(w, "| pass | reboot-proven | runtime-only | fail | pending | error | n/a | waived |\n|---|---|---|---|---|---|---|---|\n| %d | %d | %d | %d | %d | %d | %d | %d |\n\n",
		c.Pass, c.RebootProven, c.RuntimeOnly, c.Fail, c.Pending, c.Error, c.Skip, c.Waived)
	fmt.Fprintf(w, "| # | Pillar | Grade | Score | Pass |\n|---|---|---|---|---|\n")
	titles := map[int]string{}
	for _, p := range r.Pillars {
		titles[p.ID] = p.Title
	}
	for _, p := range s.Pillars {
		sc := "n/a"
		if p.Score != nil {
			sc = fmt.Sprintf("%.1f", *p.Score)
		}
		fmt.Fprintf(w, "| %02d | %s | %s | %s | %d/%d |\n", p.ID, titles[p.ID], p.Grade, sc, p.Counts.Pass, p.Counts.Pass+p.Counts.Fail+p.Counts.Error)
	}
	var bad []model.ControlResult
	for _, cr := range r.Controls {
		if score.InLens(cr, s.Lens) && (cr.Status == model.Fail || cr.Status == model.Error) {
			bad = append(bad, cr)
		}
	}
	bySeverity(bad)
	if len(bad) > 0 {
		fmt.Fprintf(w, "\n### Failures\n\n| Severity | Control | Title | Evidence | Fix |\n|---|---|---|---|---|\n")
		for _, cr := range bad {
			ev := strings.Join(failingEvidence(cr, 1), " ")
			if cr.Status == model.Error {
				ev = "error: " + cr.Reason
			}
			if cr.Qualifier == model.Pending {
				ev = "pending reboot/reload · " + ev
			}
			if cr.Proof != nil && cr.Proof.Reboot == model.ProofLost {
				ev = "lost at the reboot · " + ev
			}
			fix := "manual"
			if cr.Remediation.Auto {
				fix = "auto"
			}
			fmt.Fprintf(w, "| %s | `%s` | %s | %s | %s |\n", cr.Severity, cr.ID, mdEscape(cr.Title), mdEscape(trunc(ev, 160)), fix)
		}
	}
	fmt.Fprintf(w, "\n<sub>Generated by Shadow-Armor %s on %s.</sub>\n", r.Tool.Version, r.GeneratedAt.Format("2006-01-02 15:04 MST"))
	return nil
}

func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "<", "&lt;")
	return s
}

// JUnit writes one test suite per pillar, one test case per control.
func JUnit(w io.Writer, r *model.Report) error {
	type failure struct {
		Message string `xml:"message,attr"`
		Type    string `xml:"type,attr"`
		Text    string `xml:",chardata"`
	}
	type skipped struct {
		Message string `xml:"message,attr"`
	}
	type testcase struct {
		Name      string   `xml:"name,attr"`
		Classname string   `xml:"classname,attr"`
		Failure   *failure `xml:"failure,omitempty"`
		Error     *failure `xml:"error,omitempty"`
		Skipped   *skipped `xml:"skipped,omitempty"`
	}
	type suite struct {
		Name     string     `xml:"name,attr"`
		Tests    int        `xml:"tests,attr"`
		Failures int        `xml:"failures,attr"`
		Errors   int        `xml:"errors,attr"`
		Skipped  int        `xml:"skipped,attr"`
		Cases    []testcase `xml:"testcase"`
	}
	type suites struct {
		XMLName xml.Name `xml:"testsuites"`
		Name    string   `xml:"name,attr"`
		Suites  []suite  `xml:"testsuite"`
	}
	titles := map[int]string{}
	for _, p := range r.Pillars {
		titles[p.ID] = p.Title
	}
	byPillar := map[int]*suite{}
	var order []int
	for _, cr := range r.Controls {
		if !score.InLens(cr, r.Summary.Lens) {
			continue
		}
		s, ok := byPillar[cr.Pillar]
		if !ok {
			s = &suite{Name: fmt.Sprintf("%02d %s", cr.Pillar, titles[cr.Pillar])}
			byPillar[cr.Pillar] = s
			order = append(order, cr.Pillar)
		}
		tc := testcase{Name: cr.ID + " " + cr.Title, Classname: "shadow-armor." + fmt.Sprintf("p%02d", cr.Pillar)}
		switch cr.Status {
		case model.Fail:
			msg := cr.Severity
			if cr.Qualifier == model.Pending {
				msg += ", pending reboot/reload"
			}
			tc.Failure = &failure{Message: msg, Type: cr.Severity, Text: strings.Join(failingEvidence(cr, 10), "\n")}
			s.Failures++
		case model.Error:
			tc.Error = &failure{Message: cr.Reason, Type: "error"}
			s.Errors++
		case model.Skip, model.Waived:
			tc.Skipped = &skipped{Message: cr.Reason}
			s.Skipped++
		}
		s.Tests++
		s.Cases = append(s.Cases, tc)
	}
	sort.Ints(order)
	out := suites{Name: "Shadow-Armor " + r.Target.URI}
	for _, id := range order {
		out.Suites = append(out.Suites, *byPillar[id])
	}
	fmt.Fprint(w, xml.Header)
	enc := xml.NewEncoder(w)
	enc.Indent("", "  ")
	if err := enc.Encode(out); err != nil {
		return err
	}
	_, err := fmt.Fprintln(w)
	return err
}

// SARIF writes a SARIF 2.1.0 log (GitHub code scanning, GitLab, DefectDojo).
// Findings point at the profile control that detected them.
func SARIF(w io.Writer, r *model.Report) error {
	type msg struct {
		Text string `json:"text"`
	}
	type rule struct {
		ID               string         `json:"id"`
		Name             string         `json:"name"`
		ShortDescription msg            `json:"shortDescription"`
		FullDescription  msg            `json:"fullDescription"`
		Help             msg            `json:"help"`
		Properties       map[string]any `json:"properties"`
		DefaultConfig    map[string]any `json:"defaultConfiguration"`
	}
	type location struct {
		PhysicalLocation map[string]any `json:"physicalLocation"`
	}
	type result struct {
		RuleID     string         `json:"ruleId"`
		Level      string         `json:"level"`
		Message    msg            `json:"message"`
		Locations  []location     `json:"locations"`
		Properties map[string]any `json:"properties,omitempty"`
		Partial    map[string]any `json:"partialFingerprints,omitempty"`
	}
	level := func(sev string) string {
		switch sev {
		case "critical", "high":
			return "error"
		case "medium":
			return "warning"
		}
		return "note"
	}
	secSev := map[string]string{"critical": "9.5", "high": "8.0", "medium": "5.5", "low": "3.0", "info": "0.0"}
	var rules []rule
	var results []result
	for _, cr := range r.Controls {
		if !score.InLens(cr, r.Summary.Lens) {
			continue
		}
		tags := []string{"security", "compliance", fmt.Sprintf("pillar-%02d", cr.Pillar)}
		help := cr.Remediation.Summary
		if !cr.Remediation.Auto && cr.Remediation.Manual != "" {
			help += "\n\n" + cr.Remediation.Manual
		}
		rules = append(rules, rule{
			ID: cr.ID, Name: strings.ReplaceAll(cr.Title, " ", ""),
			ShortDescription: msg{cr.Title}, FullDescription: msg{cr.Title}, Help: msg{help},
			Properties:    map[string]any{"tags": tags, "security-severity": secSev[cr.Severity], "mappings": cr.Map},
			DefaultConfig: map[string]any{"level": level(cr.Severity)},
		})
		if cr.Status != model.Fail && cr.Status != model.Error {
			continue
		}
		text := cr.Title
		if ev := failingEvidence(cr, 3); len(ev) > 0 {
			text += ": " + strings.Join(ev, "; ")
		}
		if cr.Status == model.Error {
			text += " (could not be evaluated: " + cr.Reason + ")"
		}
		uri, line := "profile/controls", 1
		if cr.Source != "" {
			parts := strings.SplitN(cr.Source, ":", 2)
			uri = parts[0]
			if len(parts) == 2 {
				if _, err := fmt.Sscanf(parts[1], "%d", &line); err != nil {
					line = 1
				}
			}
		}
		results = append(results, result{
			RuleID: cr.ID, Level: level(cr.Severity), Message: msg{text},
			Locations: []location{{PhysicalLocation: map[string]any{
				"artifactLocation": map[string]any{"uri": uri},
				"region":           map[string]any{"startLine": line},
			}}},
			Properties: map[string]any{"target": r.Target.URI, "qualifier": string(cr.Qualifier)},
			Partial:    map[string]any{"shadowArmorTarget/v1": r.Target.URI + "#" + cr.ID},
		})
	}
	log := map[string]any{
		"$schema": "https://json.schemastore.org/sarif-2.1.0.json",
		"version": "2.1.0",
		"runs": []any{map[string]any{
			"tool": map[string]any{"driver": map[string]any{
				"name": "Shadow-Armor", "version": r.Tool.Version, "semanticVersion": strings.TrimPrefix(r.Tool.Version, "v"),
				"informationUri": "https://github.com/Shadow-Security-official/Shadow-Armor",
				"rules":          rules,
			}},
			"automationDetails": map[string]any{"id": "shadow-armor/" + r.Target.URI},
			"results":           results,
		}},
	}
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(log)
}
