package harden

import (
	"context"
	"errors"
	"fmt"
	"io"
	"strings"

	shadowarmor "github.com/Shadow-Security-official/Shadow-Armor"
	"github.com/Shadow-Security-official/Shadow-Armor/internal/cinc"
	"github.com/Shadow-Security-official/Shadow-Armor/internal/scan"
	"github.com/Shadow-Security-official/Shadow-Armor/internal/target"
)

// ErrClientMissing: no cinc-client on the target and no --bootstrap-cinc.
var ErrClientMissing = errors.New("cinc-client is not installed on the target")

// Options of a Chef run.
type Options struct {
	WhyRun        bool
	BootstrapCINC bool
	CINCVersion   string
	CINCPackages  []string
	Out           io.Writer
	Progress      func(string)
	// OnConverge is called right before cinc-client starts.
	OnConverge func()
}

// Apply stages the embedded cookbook and the plan on the target and runs
// cinc-client in local mode. Nothing stays behind except the run journal and
// Chef's file backups under /var/lib/shadow-armor.
func Apply(ctx context.Context, t *target.Target, p *Plan, o Options) error {
	progress := func(f string, a ...any) {
		if o.Progress != nil {
			o.Progress(fmt.Sprintf(f, a...))
		}
	}
	client, ok := t.Has(ctx, "cinc-client")
	if !ok {
		client, ok = t.Has(ctx, "chef-client")
	}
	if !ok {
		copts := cinc.Options{Version: o.CINCVersion, Packages: o.CINCPackages, Log: o.Out, Progress: o.Progress}
		if !o.BootstrapCINC && copts.PackageFor(cinc.Client) == "" {
			return fmt.Errorf("%w (%s): install it (sdw-armor install-cinc %s --client --sudo) or re-run with --bootstrap-cinc to install a SHA-256 verified package", ErrClientMissing, t, t)
		}
		if err := scan.Bootstrap(ctx, t, cinc.Client, copts); err != nil {
			return err
		}
		if client, ok = t.Has(ctx, "cinc-client"); !ok {
			return fmt.Errorf("cinc-client still not found on %s after bootstrap", t)
		}
	}
	// Not /tmp: fixing SA-02.20 may mount a fresh tmpfs over it mid-run.
	dir, err := t.MkTemp(ctx, "sdw-armor-harden", "/var/tmp")
	if err != nil {
		return err
	}
	defer t.Remove(ctx, dir, true)
	progress("staging cookbook and plan on %s", t)
	if err := t.Upload(ctx, shadowarmor.Cookbook, "cookbook", dir+"/cookbooks"); err != nil {
		return err
	}
	attrs, err := p.Attributes()
	if err != nil {
		return err
	}
	if err := t.WriteFile(ctx, dir+"/attrs.json", attrs); err != nil {
		return err
	}
	clientRB := fmt.Sprintf(`# Generated by sdw-armor
chef_repo_path %[1]q
cookbook_path [%[2]q]
node_path %[3]q
file_cache_path %[4]q
file_backup_path "/var/lib/shadow-armor/backup"
local_mode true
log_level :warn
`, dir, dir+"/cookbooks", dir+"/nodes", dir+"/cache")
	if err := t.WriteFile(ctx, dir+"/client.rb", []byte(clientRB)); err != nil {
		return err
	}
	args := []string{target.Quote(client), "--local-mode", "--config", target.Quote(dir + "/client.rb"),
		"--json-attributes", target.Quote(dir + "/attrs.json"), "--override-runlist", "'recipe[shadow_armor]'",
		"--no-color", "--force-formatter", "--format", "doc"}
	if o.WhyRun {
		args = append(args, "--why-run")
	}
	script := "cd " + target.Quote(dir) + " && CHEF_LICENSE=accept-no-persist " + strings.Join(args, " ")
	mode := "converging"
	if o.WhyRun {
		mode = "why-run (no change will be made)"
	}
	progress("%s with %s on %s", mode, client, t)
	if o.OnConverge != nil {
		o.OnConverge()
	}
	code, err := t.Run(ctx, script, true, nil, o.Out, o.Out)
	if err != nil {
		return err
	}
	if code != 0 {
		return fmt.Errorf("the Chef run failed on %s (exit %d): see the output above; edited files were backed up in /var/lib/shadow-armor/backup", t, code)
	}
	return nil
}
